In [15]:
import warnings
warnings.simplefilter('ignore')
import pandas as pd
import numpy as np
import os as os
os.getcwd()

'D:\\Projects\\Neuronal\\mlcourse_open\\mlcourse_open\\jupyter_notebooks\\topic01_pandas_data_analysis'

In [16]:
df = pd.read_csv('../../data/telecom_churn.csv')
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [17]:
ad = pd.read_csv('../../data/adult.data.csv')
ad.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [21]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('precision', 2)

In [22]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [23]:
ad.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [37]:
print("df:", df.shape, df.columns)
print("ad:", ad.shape, ad.columns)

df: (3333, 20) Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')
ad: (32561, 15) Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
State                     3333 non-null object
Account length            3333 non-null int64
Area code                 3333 non-null int64
International plan        3333 non-null object
Voice mail plan           3333 non-null object
Number vmail messages     3333 non-null int64
Total day minutes         3333 non-null float64
Total day calls           3333 non-null int64
Total day charge          3333 non-null float64
Total eve minutes         3333 non-null float64
Total eve calls           3333 non-null int64
Total eve charge          3333 non-null float64
Total night minutes       3333 non-null float64
Total night calls         3333 non-null int64
Total night charge        3333 non-null float64
Total intl minutes        3333 non-null float64
Total intl calls          3333 non-null int64
Total intl charge         3333 non-null float64
Customer service calls    3333 non-null int64
Churn                     3333 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

In [42]:
ad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
salary            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [47]:
df["Churn"] = df["Churn"].astype("int64")
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
count,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00
mean,101.06,437.18,8.10,179.78,100.44,30.56,200.98,100.11,17.08,200.87,100.11,9.04,10.24,4.48,2.76,1.56,0.14
std,39.82,42.37,13.69,54.47,20.07,9.26,50.71,19.92,4.31,50.57,19.57,2.28,2.79,2.46,0.75,1.32,0.35
min,1.00,408.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,23.20,33.00,1.04,0.00,0.00,0.00,0.00,0.00
25%,74.00,408.00,0.00,143.70,87.00,24.43,166.60,87.00,14.16,167.00,87.00,7.52,8.50,3.00,2.30,1.00,0.00
50%,101.00,415.00,0.00,179.40,101.00,30.50,201.40,100.00,17.12,201.20,100.00,9.05,10.30,4.00,2.78,1.00,0.00
75%,127.00,510.00,20.00,216.40,114.00,36.79,235.30,114.00,20.00,235.30,113.00,10.59,12.10,6.00,3.27,2.00,0.00
max,243.00,510.00,51.00,350.80,165.00,59.64,363.70,170.00,30.91,395.00,175.00,17.77,20.00,20.00,5.40,9.00,1.00

In [49]:
ad.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.00,3.26e+04,32561.00,32561.00,32561.00,32561.00
mean,38.58,1.90e+05,10.08,1077.65,87.30,40.44
std,13.64,1.06e+05,2.57,7385.29,402.96,12.35
min,17.00,1.23e+04,1.00,0.00,0.00,1.00
25%,28.00,1.18e+05,9.00,0.00,0.00,40.00
50%,37.00,1.78e+05,10.00,0.00,0.00,40.00
75%,48.00,2.37e+05,12.00,0.00,0.00,45.00
max,90.00,1.48e+06,16.00,99999.00,4356.00,99.00

In [65]:
df.describe(include=['object', 'bool'])

       State International plan Voice mail plan
count   3333               3333            3333
unique    51                  2               2
top       WV                 No              No
freq     106               3010            2411

In [77]:
df.Churn.value_counts(normalize=True)

0    0.86
1    0.14
Name: Churn, dtype: float64

In [79]:
ad.salary.value_counts(normalize=True)

<=50K    0.76
>50K     0.24
Name: salary, dtype: float64

In [90]:
ad.sort_values(by='age',ascending=False).head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
5406,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K
6624,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
20610,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
1040,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
1935,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K

In [92]:
df.sort_values(by='Total day charge', ascending=False)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
365,CO,154,415,No,No,0,350.8,75,59.64,216.5,94,18.40,253.9,100,11.43,10.1,9,2.73,1,1
985,NY,64,415,Yes,No,0,346.8,55,58.96,249.5,79,21.21,275.4,102,12.39,13.3,9,3.59,1,1
2594,OH,115,510,Yes,No,0,345.3,81,58.70,203.4,106,17.29,217.5,107,9.79,11.8,8,3.19,1,1
156,OH,83,415,No,No,0,337.4,120,57.36,227.4,116,19.33,153.9,114,6.93,15.8,7,4.27,0,1
605,MO,112,415,No,No,0,335.5,77,57.04,212.5,109,18.06,265.0,132,11.93,12.7,8,3.43,2,1
975,DE,129,510,No,No,0,334.3,118,56.83,192.1,104,16.33,191.0,83,8.59,10.4,6,2.81,0,1
15,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,1
1679,OK,82,510,No,No,0,329.8,73,56.07,208.3,120,17.71,267.1,102,12.02,10.6,6,2.86,0,1
2028,SD,93,510,No,No,0,328.1,106,55.78,151.7,89,12.89,303.5,114,13.66,8.7,3,2.35,1,1
197,TX,208,510,No,No,0,326.5,67,55.51,176.3,113,14.99,181.7,102,8.18,10.7,6,2.89,2,1
2412,WI,89,415,No,No,0,326.3,112,55.47,165.1,110,14.03,162.9,97,7.33,7.5,1,2.03,1,1
2824,OR,81,415,No,No,0,324.7,48,55.20,236.4,82,20.09,187.6,78,8.44,13.1,5,3.54,0,1
832,SC,87,408,No,No,0,322.5,106,54.83,204.6,93,17.39,186.2,128,8.38,9.4,4,2.54,2,1
2629,NH,141,415,No,Yes,32,322.4,92,54.81,283.2,107,24.07,209.5,111,9.43,6.7,3,1.81,1,1
3132,NC,161,415,No,No,0,322.3,100,54.79,230.4,135,19.58,241.5,104,10.87,7.8,5,2.11,2,1
1078,ME,80,408,No,No,0,322.3,113,54.79,222.0,95,18.87,162.8,123,7.33,6.7,8,1.81,0,1
901,CT,23,510,No,No,0,321.6,107,54.67,251.6,115,21.39,141.1,158,6.35,11.3,3,3.05,2,1
1334,KS,126,408,No,No,0,321.3,99,54.62,167.9,93,14.27,193.6,106,8.71,8.0,4,2.16,1,1
3322,MD,62,408,No,No,0,321.1,105,54.59,265.5,122,22.57,180.5,72,8.12,11.5,2,3.11,4,1
2572,MN,152,415,No,No,0,317.8,60,54.03,152.9,100,13.00,123.4,63,5.55,10.4,7,2.81,1,1
688,MN,13,510,No,Yes,21,315.6,105,53.65,208.9,71,17.76,260.1,123,11.70,12.1,3,3.27,3,0
815,KY,75,415,No,No,0,314.6,102,53.48,169.8,86,14.43,285.1,100,12.83,5.7,3,1.54,2,1
2696,MI,74,415,No,No,0,314.1,86,53.40,222.4,99,18.90,259.0,121,11.66,12.3,5,3.32,3,1
2259,NC,210,415,No,Yes,31,313.8,87,53.35,147.7,103,12.55,192.7,97,8.67,10.1,7,2.73,3,0
2267,MS,29,510,No,No,0,313.2,103,53.24,216.3,151,18.39,218.4,106,9.83,12.8,4,3.46,2,1
230,MD,93,408,Yes,No,0,312.0,109,53.04,129.4,100,11.00,217.6,74,9.79,10.5,2,2.84,0,1
2573,WV,124,415,No,No,0,312.0,112,53.04,180.0,109,15.30,168.6,94,7.59,12.8,4,3.46,1,1
534,LA,67,510,No,No,0,310.4,97,52.77,66.5,123,5.65,246.5,99,11.09,9.2,10,2.48,4,0
575,SD,114,415,No,Yes,36,309.9,90,52.68,200.3,89,17.03,183.5,105,8.26,14.2,2,3.83,1,0
2677,IA,44,415,No,No,0,308.6,139,52.46,150.8,94,12.82,198.7,66,8.94,7.3,3,1.97,4,1
2858,AL,141,510,No,Yes,28,308.0,123,52.36,247.8,128,21.06,152.9,103,6.88,7.4,3,2.00,1,0
1165,VT,50,415,Yes,Yes,26,307.1,94,52.21,289.4,78,24.60,174.9,109,7.87,8.0,3,2.16,0,0
3207,DC,93,408,No,Yes,22,306.2,123,52.05,189.7,83,16.12,240.3,107,10.81,11.7,2,3.16,0,0
2478,TN,123,415,No,Yes,34,305.2,80,51.88,156.5,109,13.30,280.0,81,12.60,13.2,7,3.56,1,0
3072,TX,75,415,No,No,0,305.1,106,51.87,188.0,115,15.98,235.4,116,10.59,8.5,5,2.30,0,1
2376,NV,42,415,No,No,0,303.9,106,51.66,232.2,54,19.74,147.1,76,6.62,5.8,3,1.57,1,1
289,OK,89,510,No,No,0,303.9,95,51.66,260.9,114,22.18,312.1,89,14.04,5.3,3,1.43,1,1
2215,MS,13,415,No,No,0,303.2,133,51.54,170.5,86,14.49,227.6,80,10.24,11.5,3,3.11,0,1
1355,TX,50,408,No,Yes,31,302.7,93,51.46,240.5,119,20.44,193.9,103,8.73,13.6,14,3.67,3,0
1830,CT,50,408,No,No,0,301.7,82,51.29,167.1,118,14.20,72.2,89,3.25,10.5,6,2.84,1,0
2660,NJ,88,415,No,No,0,301.5,136,51.26,257.7,72,21.90,132.9,118,5.98,13.4,2,3.62,4,1
732,IN,48,510,No,No,0,300.4,94,51.07,133.2,103,11.32,197.4,94,8.88,7.2,5,1.94,2,0
76,DC,82,415,No,No,0,300.3,109,51.05,181.0,100,15.39,270.1,73,12.15,11.7,4,3.16,0,1
629,GA,76,415,No,No,0,299.5,125,50.92,226.7,92,19.27,210.7,134,9.48,13.7,4,3.70,0,1
2149,IA,120,415,No,Yes,33,299.5,83,50.92,163.4,84,13.89,146.7,88,6.60,11.6,5,3.13,0,0
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
2614,NH,125,415,Yes,No,0,298.4,78,50.73,270.5,142,22.99,107.3,84,4.83,12.2,2,3.29,0,1
2103,NH,74,408,No,No,0,298.1,112,50.68,201.3,100,17.11,214.7,88,9.66,9.7,4,2.62,2,1
2388,SC,161,510,No,No,0,297.9,141,50.64,238.1,107,20.24,240.5,93,10.82,8.9,5,2.40,1,1
307,IN,122,408,No,No,0,296.4,99,50.39,214.8,89,18.26,133.9,107,6.03,11.4,3,3.08,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,ME,100,510,No,Yes,30,58.8,104,10.00,219.5,107,18.66,152.3,118,6.85,7.1,3,1.92,0,0
1351,LA,13,415,No,No,0,58.4,121,9.93,262.2,64,22.29,159.0,115,7.15,11.9,5,3.21,1,0
2973,NE,95,510,No,No,0,58.2,96,9.89,202.1,126,17.18,210.5,97,9.47,10.4,5,2.81,0,0
181,AK,126,415,No,No,0,58.2,94,9.89,138.7,118,11.79,136.8,91,6.16,11.9,1,3.21,5,1
2859,WV,87,415,No,No,0,58.0,125,9.86,67.5,116,5.74,185.9,136,8.37,11.5,3,3.11,0,0
603,MI,53,415,No,No,0,57.5,95,9.78,265.5,131,22.57,244.3,128,10.99,11.6,6,3.13,3,0
735,DC,169,415,Yes,No,0,57.1,98,9.71,199.7,78,16.97,274.7,103,12.36,6.5,6,1.76,3,0
3010,FL,185,408,No,No,0,55.6,97,9.45,288.7,83,24.54,111.2,110,5.00,12.1,3,3.27,2,0
2434,ID,88,415,No,No,0,55.6,65,9.45,242.7,121,20.63,176.3,134,7.93,11.3,4,3.05,0,0
585,AR,110,408,No,No,0,55.3,102,9.40,164.7,124,14.00,200.7,108,9.03,10.2,5,2.75,1,0
1642,TN,99,408,No,No,0,54.8,92,9.32,173.0,103,14.71,195.1,125,8.78,7.5,3,2.03,1,0
2792,NC,129,415,No,No,0,54.7,131,9.30,256.1,105,21.77,176.6,135,7.95,11.1,4,3.00,1,0
1837,NH,117,510,Yes,No,0,54.2,100,9.21,303.2,84,25.77,171.8,84,7.73,8.6,2,2.32,1,1
2798,MN,30,408,No,No,0,54.0,68,9.18,179.3,96,15.24,247.2,101,11.12,10.2,8,2.75,1,0
1550,SC,106,408,No,No,0,52.2,106,8.87,220.1,113,18.71,112.3,95,5.05,11.4,2,3.08,2,0
1384,CT,141,408,No,No,0,51.9,108,8.82,162.0,83,13.77,223.5,115,10.06,10.1,3,2.73,3,0
2375,OR,51,510,No,No,0,51.8,107,8.81,230.2,104,19.57,227.5,118,10.24,10.4,4,2.81,2,0
2762,DC,80,408,No,No,0,51.5,90,8.76,164.0,98,13.94,169.4,80,7.62,9.5,4,2.57,3,0
3294,MO,116,408,No,No,0,51.1,106,8.69,208.6,137,17.73,198.0,92,8.91,12.3,3,3.32,1,0
2497,MN,79,408,No,Yes,32,50.6,62,8.60,201.4,87,17.12,146.8,121,6.61,4.2,4,1.13,2,0
2303,IN,205,510,No,No,0,49.9,123,8.48,150.7,81,12.81,188.2,67,8.47,10.1,4,2.73,2,0
2703,CT,162,408,No,No,0,49.2,121,8.36,143.9,136,12.23,203.0,97,9.14,12.1,13,3.27,1,0
535,NE,194,408,No,No,0,48.4,101,8.23,281.1,138,23.89,218.5,87,9.83,18.2,1,4.91,1,0
2173,KS,47,510,Yes,No,0,47.8,120,8.13,178.9,123,15.21,152.6,96,6.87,13.3,7,3.59,0,1
2158,FL,166,510,Yes,No,0,47.7,89,8.11,264.4,95,22.47,235.2,97,10.58,13.2,3,3.56,0,1
525,OK,176,408,No,No,0,47.4,125,8.06,167.8,90,14.26,163.1,107,7.34,10.5,8,2.84,2,0
1531,DE,138,510,Yes,No,0,46.5,104,7.91,186.0,114,15.81,167.5,95,7.54,9.6,4,2.59,4,1
523,MO,61,408,No,No,0,45.0,108,7.65,151.3,74,12.86,152.9,94,6.88,9.8,6,2.65,2,0
2996,VA,113,408,No,Yes,34,44.9,63,7.63,134.2,82,11.41,168.4,118,7.58,13.3,3,3.59,1,0
1742,HI,79,415,No,No,0,41.9,124,7.12,211.0,95,17.94,237.9,55,10.71,11.4,5,3.08,1,0
527,NJ,95,415,No,Yes,22,40.9,126,6.95,133.4,90,11.34,264.2,91,11.89,11.9,7,3.21,0,0
2707,RI,46,408,No,No,0,40.4,105,6.87,172.4,83,14.65,145.1,89,6.53,9.0,2,2.43,2,0
1461,SC,145,408,No,No,0,39.5,78,6.72,264.3,106,22.47,185.8,90,8.36,10.0,6,2.70,0,0
1687,CT,90,415,No,No,0,37.8,80,6.43,155.3,105,13.20,175.0,111,7.88,14.2,5,3.83,3,0
2241,WA,56,415,No,Yes,29,37.7,115,6.41,144.1,111,12.25,226.6,101,10.20,4.9,3,1.32,1,0
1130,PA,122,415,No,No,0,35.1,62,5.97,180.8,89,15.37,251.6,58,11.32,12.7,2,3.43,1,0
741,NE,66,415,No,No,0,34.0,133,5.78,278.6,61,23.68,129.6,120,5.83,11.5,3,3.11,0,0
685,CO,63,415,No,Yes,32,30.9,113,5.25,187.0,113,15.90,230.8,101,10.39,8.6,7,2.32,1,0
3174,SC,36,408,No,Yes,43,29.9,123,5.08,129.1,117,10.97,325.9,105,14.67,8.6,6,2.32,2,0
2124,KS,43,415,No,No,0,27.0,117,4.59,160.9,97,13.68,279.5,96,12.58,10.7,3,2.89,3,0
1076,WY,53,415,No,Yes,27,25.9,119,4.40,206.5,96,17.55,228.1,64,10.26,6.5,7,1.76,1,0
1621,SC,138,510,No,Yes,21,19.5,149,3.32,140.9,109,11.98,179.7,111,8.09,7.9,1,2.13,0,0
3046,MI,110,510,No,No,0,18.9,92,3.21,258.4,81,21.96,109.6,74,4.93,14.8,4,4.00,1,0
2252,NH,148,408,No,No,0,17.6,121,2.99,161.7,125,13.74,203.1,82,9.14,10.6,6,2.86,1,0
1052,OR,98,415,Yes,No,0,12.5,67,2.13,256.6,90,21.81,169.4,88,7.62,7.7,9,2.08,1,0
1986,WI,70,415,No,No,0,7.9,100,1.34,136.4,83,11.59,156.6,89,7.05,12.1,1,3.27,0,0
2753,OH,134,415,No,No,0,7.8,86,1.33,171.4,100,14.57,186.5,80,8.39,12.9,2,3.48,2,0
2736,OK,127,510,No,Yes,27,2.6,113,0.44,254.0,102,21.59,242.7,156,10.92,9.2,5,2.48,3,0
1397,VT,101,510,No,No,0,0.0,0,0.00,192.1,119,16.33,168.8,95,7.60,7.2,4,1.94,1,0
1345,SD,98,415,No,No,0,0.0,0,0.00,159.6,130,13.57,167.1,88,7.52,6.8,1,1.84,4,1